from .register import *
from .login import *
from .account_active import *
from .reset_password import *
from .profile import *
from .otp_email import *
from .account_active import *
from .carbon_credit import *
from .sludgify_analysis import *
from .transaction_payment import *
from .company_information import *
from .calculator import *
from .download import *
from .chat_bot import *
